@echo off
echo === Airline System ===
cd /d D:\Projects\3.Airline System
echo Installing dependencies...
python -m pip install -r requirements.txt -q
echo Running migrations...
python manage.py migrate
echo Starting server...
python manage.py runserver 8000
